first commit
SBlinsk/Chat pull request #1
Opened 2023-04-11 15:40 UTC by SBlinsk

Чат
На экране окошко чата. Внизу окна поле для ввода текста и кнопка “отправить”. После
отправки сообщения оно появляется в окошке чата.
В течении 1-3 секунд после отправки сообщения, Вам отвечает бот. Сообщение в чате от
бота должно визуально отличаться от Вашего. Бот отвечает случайным сообщением из
заготовленного списка ответов.
Если Вы попрощались с ботом (например, отправили сообщение “Ой, все”), бот должен
попрощаться в ответ и больше не отвечать на Ваши сообщения.
Нужно использовать async/await для асинхронных ответов бота. Старайтесь использовать
как можно больше из ES6.

2023-04-11 20:13 UTC, dkhovrich requested changes

2023-04-11 20:13 UTC, dkhovrich commented on Form.js
> +      chatWindow.style.width = "250px";
Лучше добавить имя класса и перенести стили в css.

2023-04-11 20:13 UTC, dkhovrich commented on Input.js
> +    input.style.width = "198px";
Тоже через css лучше.

2023-04-11 20:13 UTC, dkhovrich commented on Chat.js
> +    function wait(ms) {
Эту функцию лучше вынести за пределы класса.

2023-04-11 20:13 UTC, dkhovrich commented on Chat.js
> +      async function answerWithDelay() {
Сам обработчик события сабмит может быть `async`. Тогда нет надобности в функции `answerWithDelay`.

2023-04-11 20:13 UTC, dkhovrich commented on Chat.js
> +  on() {
У этой функции ужасное название и она делает слишком много. Подумай как разбить ее на несколько более мелких функций. Эти мелкие функции будут методами класса Chat.

2023-04-11 20:13 UTC, dkhovrich commented on Chat.js
> +    const arrOfAnswers = [
Все, что касается ответов, можно вынести в класс ChatBot. У этого класса может быть метод, который возвращает случайный ответ спустя случайное время (от 1 до 3 секунд). Это будет асинхронная функция, которая возвращает строку.

2023-04-11 20:13 UTC, dkhovrich commented on Button.js
> +class Button {
Нет смысла делать класс если в нем нет полей и не используется this. Могу предложить два варианта:

- Оставить класс. В этом случае стоит перенести создание дом элемента в конструктор и прокинуть колбек, который будет вызываться по клику. То есть сделать подписку на событие внутри этого класса.
- Заменить класс на ф-цию `createButton`

2023-04-11 20:13 UTC, dkhovrich commented on Chat.js
> +        elementRemoval();
Я правильно понимаю, что ты каждый раз при добавлении нового сообщения удаляешь все предыдущие и повторно их рисуешь? Это плохо и неправильно. Надо переделать.

2023-04-11 20:13 UTC, dkhovrich commented on Chat.js
> +        await wait(2000);
Интервал должен быть случайным (от 1 до 3 секунд).

2023-04-11 20:14 UTC, dkhovrich commented on Button.js
> +class Button {
Это относится не только к классу Button, но и ко всем остальным.

2023-04-11 20:18 UTC, SBlinsk commented
Понял, завтра буду переделывать) спасибо. Доброй ночи)

BRGDS
________________________________
От: Dmitriy Khovrich ***@***.***>
Отправлено: Tuesday, April 11, 2023 10:14:20 PM
Кому: SBlinsk/Chat ***@***.***>
Копия: Sblinsk ***@***.***>; Author ***@***.***>
Тема: Re: [SBlinsk/Chat] first commit (PR #1)


@dkhovrich commented on this pull request.

________________________________

In Button.js<https://github.com/SBlinsk/Chat/pull/1#discussion_r1163277484>:

> @@ -0,0 +1,9 @@
+class Button {


Это относится не только к классу Button, но и ко всем остальным.

—
Reply to this email directly, view it on GitHub<https://github.com/SBlinsk/Chat/pull/1#discussion_r1163277484>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3GNUJQXBMZN4BV6O6VGUMDXAW3RZANCNFSM6AAAAAAW2ONZAA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-13 11:06 UTC, SBlinsk commented on Form.js
> +      chatWindow.style.width = "250px";
Done!

2023-04-13 11:11 UTC, SBlinsk commented on Input.js
> +    input.style.width = "198px";
Done

2023-04-13 11:14 UTC, SBlinsk commented on Chat.js
> +    function wait(ms) {
Done

2023-04-13 11:17 UTC, SBlinsk commented on Chat.js
> +      async function answerWithDelay() {
Done

2023-04-13 11:21 UTC, SBlinsk commented on Chat.js
> +  on() {
Ты имеешь ввиду метод on() класса Chat?

2023-04-13 12:22 UTC, dkhovrich commented on Chat.js
> +  on() {
Да.

2023-04-13 12:23 UTC, dkhovrich commented on Chat.js
> +    function wait(ms) {
Не вижу изменений. Ты их запушил?

2023-04-13 12:23 UTC, dkhovrich commented on Chat.js
> +      async function answerWithDelay() {
Не вижу изменений. Ты их запушил?

2023-04-13 12:38 UTC, SBlinsk commented on Chat.js
> +    function wait(ms) {
Я тебя понял. но я запушил их, правда через минуту как комент написал)

2023-04-13 12:38 UTC, SBlinsk commented on Chat.js
> +      async function answerWithDelay() {
очень странно

2023-04-13 12:41 UTC, SBlinsk commented on Chat.js
> +        elementRemoval();
Да, все верно, я так и делаю. Ты имеешь ввиду создавать новый элемент с новым сообщением и добавлять его в поле чата?

2023-04-13 12:42 UTC, SBlinsk commented on Chat.js
> +        await wait(2000);
Понял=)

2023-04-13 12:52 UTC, dkhovrich commented on ChatBot.js
> +        setTimeout(
У тебя есть для этого функция `wait`. Лучше использовать ее.

2023-04-13 12:53 UTC, dkhovrich commented on ChatBot.js
> +        const randomIndex = Math.floor(Math.random() * arrOfAnswers.length);
Тут выглядит так, что нужна отдельная функция. Что-то вроде `getRandomNumber(start, end)`

2023-04-13 12:54 UTC, dkhovrich commented on Chat.js
> +        elementRemoval();
Да. Не нужно каждый раз удалять все старые элементы и заново добавлять из в ДОМ.

2023-04-13 15:13 UTC, SBlinsk commented on ChatBot.js
> +        const randomIndex = Math.floor(Math.random() * arrOfAnswers.length);
Для того, чтобы заменить Math.random()?

2023-04-13 15:15 UTC, SBlinsk commented on ChatBot.js
> +        setTimeout(
Я уже ее удалил за ненадобностью ахахахах Вернуть?

2023-04-13 15:15 UTC, SBlinsk commented on Chat.js
> +        elementRemoval();
Done

2023-04-13 15:36 UTC, SBlinsk commented on Button.js
> +class Button {
Done

2023-04-13 15:36 UTC, SBlinsk commented on Chat.js
> +    const arrOfAnswers = [
Done

2023-04-13 15:36 UTC, SBlinsk commented on Chat.js
> +  on() {
Done

2023-04-13 16:16 UTC, dkhovrich commented on ChatBot.js
> +        const randomIndex = Math.floor(Math.random() * arrOfAnswers.length);
Чтобы скрыть его. Внутри он будет использоваться.

2023-04-13 16:24 UTC, dkhovrich requested changes

2023-04-13 16:24 UTC, dkhovrich commented on Chat.js
> +    const chatWindow = document.querySelector("[data-atribute= 'chatWindow']");
Попробуй сделать без `querySelector`.

2023-04-13 16:24 UTC, dkhovrich commented on Chat.js
> +      event.target.input.value="";
Подобные вещи лучше скрывать за методами класса. Конкретно здесь лучше обратиться к `this.form` и вызывать метод `clear`. Форма в свою очередь должна вызвать подобный метод у объекта `this.input`.

2023-04-13 16:24 UTC, dkhovrich commented on Chat.js
> +      answer.answerOn().then((answerText) => {
Почему не await? Лучше использовать что-то одно. Раз ты уже используешь async, то лучше тут использовать await.

2023-04-13 16:24 UTC, dkhovrich commented on Chat.js
> +  on() {
Ужасное название функции никуда не делось :)

2023-04-13 16:24 UTC, dkhovrich commented on Chat.js
> +      let value = event.target.input.value;
Подобные вещи лучше скрывать за методами класса. Конкретно здесь лучше обратиться к `this.form` и вызывать метод `getText`. Форма в свою очередь должна вызвать подобный метод у объекта `this.input`.

2023-04-13 16:24 UTC, dkhovrich commented on Chat.js
> +      let answer = new ChatBot([
Чат бот не должен создаваться каждый раз на сабмите формы. Достаточно создать объект бота один раз в конструкторе чата.

2023-04-13 16:24 UTC, dkhovrich commented on ChatBot.js
> +  getRandomAnswerWithDelay() {
```
 async getRandomAnswerWithDelay() {
const randomIndex = getRandomNumber(0, this.answers.length);
const randomDelay = getRandomNumber(0, 3) * 1000;
await wait(randomDelay);
return this.answers[randomIndex];
   }
```

2023-04-13 16:30 UTC, SBlinsk commented on Chat.js
> +  on() {
Done=)

2023-04-13 16:31 UTC, SBlinsk commented on Chat.js
> +  on() {
push)

2023-04-13 16:49 UTC, SBlinsk commented on ChatBot.js
> +        const randomIndex = Math.floor(Math.random() * arrOfAnswers.length);
Я чет не до конца понимаю зачем и как(

2023-04-13 17:14 UTC, dkhovrich commented on ChatBot.js
> +        const randomIndex = Math.floor(Math.random() * arrOfAnswers.length);
Я тебе вот тут написал как оно может выглядеть: https://github.com/SBlinsk/Chat/pull/1#discussion_r1165769486
Зачем - чтобы инкапсулировать детали реализации (все, что касается объекта Math) и не дублировать код.

2023-04-13 17:15 UTC, dkhovrich commented on ChatBot.js
> +        const randomIndex = Math.floor(Math.random() * arrOfAnswers.length);
Вот пример такой функции. https://stackoverflow.com/a/1527820/3605764

2023-04-18 11:18 UTC, SBlinsk commented on Chat.js
> +        await wait(2000);
Done

2023-04-18 11:54 UTC, SBlinsk commented on ChatBot.js
> +        const randomIndex = Math.floor(Math.random() * arrOfAnswers.length);
Done=)

2023-04-18 12:12 UTC, SBlinsk commented on Chat.js
> +    const chatWindow = document.querySelector("[data-atribute= 'chatWindow']");
Done, but better check please, I think my solution is not the best because it is not on the principle of 'Abstraction'.=)

2023-04-18 14:53 UTC, SBlinsk commented on Chat.js
> +      event.target.input.value="";
Done=) I had to redo all the classes correctly, I think I finally figured out how to use them correctly.

2023-04-18 14:54 UTC, SBlinsk commented on Chat.js
> +      let value = event.target.input.value;
Done=)

2023-04-18 14:56 UTC, SBlinsk commented on Chat.js
> +      let answer = new ChatBot([
Done=)

2023-04-18 15:07 UTC, SBlinsk commented on ChatBot.js
> +  getRandomAnswerWithDelay() {
Done

2023-04-18 15:15 UTC, SBlinsk commented on Chat.js
> +      answer.answerOn().then((answerText) => {
Done

2023-04-18 16:42 UTC, dkhovrich approved these changes
Хорошая работа! Ты стал лучше понимать зачем нужны классы и как их использовать.

2023-04-18 16:42 UTC, dkhovrich commented on Chat.js
> +    this.chatMessage = new ChatMessage();
Это поле нигде не используется.

2023-04-18 16:42 UTC, dkhovrich commented on Form.js
> +    let value = this.input.getValue();
const, т.к. переменная нигде не меняется

2023-04-18 16:42 UTC, dkhovrich commented on Input.js
> +    return this.input.value;
Подобные функции обычно не возвращают результат. Тут всегда будет возвращаться пустая строка. Она нужна потребителю этого метода?

2023-04-19 11:09 UTC, SBlinsk commented on Input.js
> +    return this.input.value;
Наверное нет=)

2023-04-19 11:10 UTC, merged